"""ai gov + merkle + policy v1.6

Revision ID: 6ba0888e21c1
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '6ba0888e21c1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_systems',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=False),
    sa.Column('impact_assessment', sa.Boolean(), nullable=False),
    sa.Column('data_governance', sa.Boolean(), nullable=False),
    sa.Column('human_oversight', sa.Boolean(), nullable=False),
    sa.Column('transparency_notice', sa.Boolean(), nullable=False),
    sa.Column('eval_report', sa.Boolean(), nullable=False),
    sa.Column('logging_enabled', sa.Boolean(), nullable=False),
    sa.Column('accuracy_tested', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_tenant_id'), 'ai_systems', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=256), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_source_system'), 'assets', ['source_system'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('compliance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_snapshots_captured_at'), 'compliance_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_compliance_snapshots_tenant_id'), 'compliance_snapshots', ['tenant_id'], unique=False)
    op.create_table('evidence_metadata',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=128), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('telemetry_hash', sa.String(length=128), nullable=False),
    sa.Column('record_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ERROR', 'NOT_APPLICABLE', 'PENDING', name='controlstatus'), nullable=False),
    sa.Column('object_uri', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_metadata_run_id'), 'evidence_metadata', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_metadata_tenant_id'), 'evidence_metadata', ['tenant_id'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=128), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ERROR', 'NOT_APPLICABLE', 'PENDING', name='controlstatus'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('lifecycle', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'RISK_ACCEPTED', name='lifecycle'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_findings_control_id'), 'findings', ['control_id'], unique=False)
    op.create_index(op.f('ix_findings_lifecycle'), 'findings', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index('ix_findings_tenant_created', 'findings', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_keys_tenant_id'), 'idempotency_keys', ['tenant_id'], unique=False)
    op.create_table('merkle_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('root', sa.String(length=128), nullable=False),
    sa.Column('leaf_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_anchors_created_at'), 'merkle_anchors', ['created_at'], unique=False)
    op.create_index(op.f('ix_merkle_anchors_tenant_id'), 'merkle_anchors', ['tenant_id'], unique=False)
    op.create_table('policy_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_id', sa.String(length=128), nullable=False),
    sa.Column('rego', sa.Text(), nullable=False),
    sa.Column('telemetry_field', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_drafts_tenant_id'), 'policy_drafts', ['tenant_id'], unique=False)
    op.create_table('posture',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('control_id', sa.String(length=128), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=256), nullable=True),
    sa.Column('asset_key', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ERROR', 'NOT_APPLICABLE', 'PENDING', name='controlstatus'), nullable=False),
    sa.Column('prev_status', sa.Enum('PASS', 'FAIL', 'ERROR', 'NOT_APPLICABLE', 'PENDING', name='controlstatus'), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('last_finding_id', sa.String(length=36), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'control_id', 'source_system', 'asset_key', name='uq_posture_key')
    )
    op.create_index('ix_posture_tenant', 'posture', ['tenant_id'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('controls', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    op.create_table('waivers',
    sa.Column('waiver_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('control_id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='exceptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('waiver_id')
    )
    op.create_index(op.f('ix_waivers_control_id'), 'waivers', ['control_id'], unique=False)
    op.create_index('ix_waivers_tenant_control_status', 'waivers', ['tenant_id', 'control_id', 'status'], unique=False)
    op.create_index(op.f('ix_waivers_tenant_id'), 'waivers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waivers_tenant_id'), table_name='waivers')
    op.drop_index('ix_waivers_tenant_control_status', table_name='waivers')
    op.drop_index(op.f('ix_waivers_control_id'), table_name='waivers')
    op.drop_table('waivers')
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_posture_tenant', table_name='posture')
    op.drop_table('posture')
    op.drop_index(op.f('ix_policy_drafts_tenant_id'), table_name='policy_drafts')
    op.drop_table('policy_drafts')
    op.drop_index(op.f('ix_merkle_anchors_tenant_id'), table_name='merkle_anchors')
    op.drop_index(op.f('ix_merkle_anchors_created_at'), table_name='merkle_anchors')
    op.drop_table('merkle_anchors')
    op.drop_index(op.f('ix_idempotency_keys_tenant_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index('ix_findings_tenant_created', table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_lifecycle'), table_name='findings')
    op.drop_index(op.f('ix_findings_control_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_evidence_metadata_tenant_id'), table_name='evidence_metadata')
    op.drop_index(op.f('ix_evidence_metadata_run_id'), table_name='evidence_metadata')
    op.drop_table('evidence_metadata')
    op.drop_index(op.f('ix_compliance_snapshots_tenant_id'), table_name='compliance_snapshots')
    op.drop_index(op.f('ix_compliance_snapshots_captured_at'), table_name='compliance_snapshots')
    op.drop_table('compliance_snapshots')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_source_system'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_ai_systems_tenant_id'), table_name='ai_systems')
    op.drop_table('ai_systems')
    # ### end Alembic commands ###
